Add highlight_changes parameter to world inspector
jakobhellermann/bevy-inspector-egui pull request #38
Opened 2021-11-23 13:39 UTC by jamesbeilby

Optionally highlights component when they change in the world (detected using component ticks).
Expanded "world" example to demonstrate.

https://user-images.githubusercontent.com/27224353/143033960-a128b525-f75f-467a-bd99-dbe6139a46e2.mp4

2021-11-23 17:05 UTC, jakobhellermann requested changes
Thanks a lot, this looks useful to have! I added some small comments, notably the functions should still be unsafe, otherwise this is good to merge.

2021-11-23 17:05 UTC, jakobhellermann commented on src/world_inspector/mod.rs
> +pub(crate) fn try_display(
This should still be `unsafe` because the `try_display` function requires the parameter to be valid in order to uphold memory safety.

2021-11-23 17:05 UTC, jakobhellermann commented on src/world_inspector/mod.rs
> -unsafe fn display_by_inspectable_registry(
Same here

2021-11-26 11:34 UTC, jamesbeilby commented
Thanks for the feedback! Am just working my way through Rustonomicon on `unsafe` now!
Updated with changes; also propagating unsafe up to component_ui, component_kind_ui where we depend on the entity lookup, and some extra comments.

2021-11-26 11:40 UTC, jakobhellermann approved these changes

2021-11-26 11:40 UTC, merged